### ISSUE TITLE
Inconsistent serde implementations

### ISSUE THREAD

**Issue by ecton** [khonsulabs/fabruic#29]
- `CertificateChain` can only be serialized via serde
- `PrivateKey` can't be serialized via serde

I was trying to store the private key and the chain in Bonsai, and I only then discovered PrivateKey doesn't implement serde through that action.

Is there a good reason to not implement it for PrivateKey?

**Comment by daxpedda** [comment]
It does over the `Dangerous` trait, as we discussed before it's probably a terrible solution. So I will change that soon to something simpler.

**Comment by ecton** [comment]
> It does over the `Dangerous` trait

So it does. I missed that. This does make it significantly easier to provide a wrapper. I close this request :)
