### ISSUE TITLE
TrustDNS Updates: Add support for localhost + `connect_with` without trust-dns

### ISSUE THREAD

**Issue by ecton** [khonsulabs/fabruic#5]
For simplifying PliantDB, there are two use cases that are helpful:

* Using `connect_with` to connect with "localhost" or an IP address without failing.
* Allowing `connect_with` to be called with trust-dns disabled, falling back to tokio's basic address resolution.

**Comment by daxpedda** [comment]
Fixed. Used std's address resolution.
https://khonsulabs.github.io/fabruic/main/fabruic/struct.Endpoint.html#method.connect
