### ISSUE TITLE
Can't listen after closing an Endpoint

### ISSUE THREAD

**Issue by ecton** [khonsulabs/fabruic#50]
I have been trying to test a client disconnect/reconnect issue in BonsaiDb, and while I had some issues in BonsaiDb, I ended up running into a bug in Fabruic. Try modifying the close() test for Endpoint by adding these lines:

```rust
		let port = server.local_address()?.port();
...
		drop(server);
		std::thread::sleep(std::time::Duration::from_secs(1));

		// Try listening again.
		let mut server = Endpoint::new_server(port, key_pair.clone())?;
		let address = format!("quic://{}", server.local_address()?);

		let _connection = client
			.connect_pinned(&address, key_pair.end_entity_certificate(), None)
			.await?
			.accept::<()>()
			.await?;
		let _connection = server.next().await.expect("client dropped");
```

This will cause the test to fail with an Address already in use error. From my viewpoint, after calling close(), the Endpoint should no longer be using the socket address, and the extra drop of the server shouldn't be needed to make this test function.

**Comment by daxpedda** [comment]
Are you saying the extra `drop(server)` makes the test actually work?

**Comment by ecton** [comment]
No, I cannot figure out how to make the test work -- I can't seem to ever reuse a port.

**Comment by ecton** [comment]
On a coworking session on Discord, @daxpedda remembered that `SO_REUSEADDR` was a flag that needs to be set for this type of situation. [This question on SO](https://stackoverflow.com/a/14388707) has a lot of information about the flag, but after adding this flag, the endpoint can properly be rebound. The pull request #51 addresses adding this option to the endpoint builder.
