### ISSUE TITLE
Support connecting using client-side certificate validation

### ISSUE THREAD

**Issue by ecton** [khonsulabs/fabruic#6]
For PliantDB, we're going to want to support connecting fabruic using a certificate chain like a standard HTTPS interface would use. Ideally, the same certificate that can be used to connect to PliantDB over HTTPS can be used to serve the QUIC connection.

The client would be responsible for validating that the certificate authority was trusted by the system and that the hostname used to connect matched an entry in the certificate.

This is not likely needed for Cosmic Verge.

**Comment by daxpedda** [comment]
Done. See https://khonsulabs.github.io/fabruic/main/fabruic/struct.Builder.html#method.set_store.
