### ISSUE TITLE
cloudflare-quic tests are failing

### ISSUE THREAD

**Issue by ecton** [khonsulabs/fabruic#68]
All of the cloudflare-quic tests are now failing, making me suspect an incompatibility between how we're negotiating the connection. There is no real error message being returned, just a ConnectionClosed blaming crypto with an error code of 120.

As far as I can tell, everything about this crate is still working correctly.

**Comment by daxpedda** [comment]
Yeah, Cloudflare dropped support for old QUIC versions, so the ALPN just had to be adjusted.
